name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: rm -rf node_modules && yarn install --immutable --immutable-cache --check-cache
      - run: yarn lint
